CREATE DATABASE user_telephones;

USE user_telephones;

CREATE TABLE PERSONAS(
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    nombre VARCHAR(10) NOT NULL,
    apellido VARCHAR(10) NOT NULL
);

CREATE TABLE TELEFONOS(
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    telefono VARCHAR(10) NOT NULL,
    tipo VARCHAR(10) NOT NULL
    FOREIGN KEY (persona_id) REFERENCES PERSONAS(id) ON DELETE CASCADE
)