CREATE DATABASE VEHICULO_CONDUCTOR;

USE VEHICULO_CONDUCTOR;

CREATE TABLE VEHICULOS(
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    num_vehiculo VARCHAR(20) NOT NULL UNIQUE,
    ruta VARCHAR (20) NOT NULL,
);

CREATE TABLE CONDUCTOR(
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    nombre_conductor VARCHAR(20) NOT NULL,
    tipo_licesia VARCHAR(10) NOT NULL,
    FOREIGN KEY (VEHICULOS_id) REFERENCES VEHICULOS(id) ON DELETE CASCADE
);